export const FIELD_INFLUENCER_NAME = "name";
export const FIELD_INFLUENCER_EMAIL = "email";
export const FIELD_INFLUENCER_PHONE = "phone";
export const FIELD_INFLUENCER_DOB = "birthday";
export const FIELD_INFLUENCER_ADDRESS = "address";
export const FIELD_INFLUENCER_PROVINCE = "city";
export const FIELD_INFLUENCER_GENDER = "sex";
export const FIELD_INFLUENCER_MARRIED = "maritalStatus";
export const FIELD_INFLUENCER_WORK = "career";
export const FIELD_INFLUENCER_WORKS = "industryId";
export const FIELD_INFLUENCER_FB = "urlFb";
export const FIELD_INFLUENCER_TT = "averageInteract";
export const FIELD_INFLUENCER_INTRO = "description";
export const FIELD_INFLUENCER_EXP = "saleExpertience";
export const FIELD_INFLUENCER_CHANEL = "channelInteraction";
export const FIELD_INFLUENCER_TYPE = "typesInteraction";
export const FIELD_INFLUENCER_BANK_A = "bankAccount";
export const FIELD_INFLUENCER_BANK_N = "bankName";
export const FIELD_INFLUENCER_AVATAR = "avatar";

export const LIST_FIELD_VALIDATE = [
  FIELD_INFLUENCER_NAME,
  FIELD_INFLUENCER_EMAIL,
  FIELD_INFLUENCER_PHONE,
  FIELD_INFLUENCER_FB,
  FIELD_INFLUENCER_DOB,
  FIELD_INFLUENCER_ADDRESS,
  FIELD_INFLUENCER_PROVINCE,
  FIELD_INFLUENCER_GENDER,
  FIELD_INFLUENCER_MARRIED,
  FIELD_INFLUENCER_WORK,
  FIELD_INFLUENCER_WORKS,
  FIELD_INFLUENCER_TT,
  FIELD_INFLUENCER_INTRO,
  FIELD_INFLUENCER_EXP,
  FIELD_INFLUENCER_CHANEL,
  FIELD_INFLUENCER_TYPE,
  FIELD_INFLUENCER_BANK_A,
  FIELD_INFLUENCER_BANK_N,
  FIELD_INFLUENCER_AVATAR,
];
